# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GWAS <- function(Y, GEN, M, NumPCs = 3L, maxit = 500L, logtol = -8, cores = 1L, verb = TRUE) {
    .Call('_mas_GWAS', PACKAGE = 'mas', Y, GEN, M, NumPCs, maxit, logtol, cores, verb)
}

MLM <- function(Y, X, Z, maxit = 500L, logtol = -8, cores = 1L) {
    .Call('_mas_MLM', PACKAGE = 'mas', Y, X, Z, maxit, logtol, cores)
}

